name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - uses: jetli/wasm-bindgen-action@v0.1.0
      with:
        # Optional version of wasm-bindgen to install(eg. '0.2.68', 'latest')
        version: 'latest'
    
    - name: Install Wasm
      run: |
        rustup target add wasm32-unknown-unknown

    - name: Build
      run: trunk build --release
      
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./dist
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./dist

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
